### PHASE 1 - LIBRARY EXPLORATION

In [17]:
import yfinance as yf
import numpy as np
stock = yf.Ticker('TCS.NS')

In [18]:
data_stock = stock.history(period='1y')
data_stock.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-05-06 00:00:00+05:30,3344.419922,3356.985661,3322.188229,3344.419922,1324763,0.0,0.0
2025-05-07 00:00:00+05:30,3306.335993,3343.936456,3306.335993,3330.017578,1477128,0.0,0.0
2025-05-08 00:00:00+05:30,3332.820588,3360.851852,3314.165252,3333.690430,2543591,0.0,0.0
2025-05-09 00:00:00+05:30,3285.457255,3331.080503,3284.587413,3325.377686,2531757,0.0,0.0
2025-05-12 00:00:00+05:30,3387.916426,3509.224132,3385.209912,3499.461426,2228678,0.0,0.0

In [19]:
print(data_stock.shape)
print(data_stock.isnull().sum())
print(data_stock.columns.to_list())

(250, 7)
Open            1
High            1
Low             1
Close           1
Volume          0
Dividends       0
Stock Splits    0
dtype: int64
['Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits']

In [20]:
import sys
sys.path.append('..')

from src.utils import get_logger

logger = get_logger("test")
print("logger created:", logger)
logger.info("hello this is a log message")

2026-05-07 00:19:01,232 - test - INFO - hello this is a log message

logger created: <Logger test (INFO)>

### PHASE 2 - DATA INGESTION

In [21]:
import sys
sys.path.append('..')
from src.data_ingestion import fetch_stock_data

df=fetch_stock_data('RELIANCE.NS','1y')
df

2026-05-07 00:19:01,241 - src.data_ingestion - INFO - Fetching data for RELIANCE.NS over the period of 1y
2026-05-07 00:19:01,383 - src.data_ingestion - INFO - Successfully fetched 250 rows for RELIANCE.NS

                                  Open        Close          Low         High
Date
2025-05-06 00:00:00+05:30  1425.307479  1415.247681  1404.988605  1426.303501
2025-05-07 00:00:00+05:30  1415.247612  1400.406860  1397.119939  1418.733689
2025-05-08 00:00:00+05:30  1398.514466  1401.402954  1392.438756  1415.148106
2025-05-09 00:00:00+05:30  1379.988467  1371.721436  1369.032225  1389.251520
2025-05-12 00:00:00+05:30  1394.430722  1430.785522  1394.430722  1433.275577
...                                ...          ...          ...          ...
2026-04-30 00:00:00+05:30  1409.000000  1430.800049  1393.099976  1437.000000
2026-05-01 00:00:00+05:30  1430.800049  1430.800049  1430.800049  1430.800049
2026-05-04 00:00:00+05:30  1433.400024  1463.099976  1433.400024  1467.400024
2026-05-05 00:00:00+05:30  1460.000000  1463.599976  1450.000000  1473.400024
2026-05-06 00:00:00+05:30          NaN          NaN          NaN          NaN

[250 rows x 4 columns]

### PHASE 3 - FEATURE ENGINEERING

In [22]:
from src.feature_engineering import calculate_daily_returns, calculate_volatility, calculate_sharpe_ratio, calculate_max_drawdown
df = fetch_stock_data('HDFCBANK.NS','1y')
df

2026-05-07 00:19:01,401 - src.data_ingestion - INFO - Fetching data for HDFCBANK.NS over the period of 1y
2026-05-07 00:19:01,493 - src.data_ingestion - INFO - Successfully fetched 250 rows for HDFCBANK.NS

                                 Open       Close         Low        High
Date
2025-05-06 00:00:00+05:30  952.130049  952.968689  949.318083  957.112687
2025-05-07 00:00:00+05:30  954.103415  959.826050  948.380780  961.355366
2025-05-08 00:00:00+05:30  964.364722  951.390076  946.752746  964.364722
2025-05-09 00:00:00+05:30  942.312757  932.248779  930.818166  946.703420
2025-05-12 00:00:00+05:30  946.012784  965.548706  943.398163  966.880738
...                               ...         ...         ...         ...
2026-04-30 00:00:00+05:30  770.000000  771.700012  762.250000  778.799988
2026-05-01 00:00:00+05:30  771.700012  771.700012  771.700012  771.700012
2026-05-04 00:00:00+05:30  772.599976  779.400024  772.599976  786.599976
2026-05-05 00:00:00+05:30  774.400024  772.299988  763.700012  776.900024
2026-05-06 00:00:00+05:30         NaN         NaN         NaN         NaN

[250 rows x 4 columns]

In [23]:
daily_return = calculate_daily_returns(df)
volatility = calculate_volatility(daily_return)
sharpe_ratio = calculate_sharpe_ratio(daily_return, volatility)
max_drawdown = calculate_max_drawdown(daily_return)

2026-05-07 00:19:01,520 - src.feature_engineering - INFO - Calculating daily returns
2026-05-07 00:19:01,524 - src.feature_engineering - INFO - Calculating annualised volatility
2026-05-07 00:19:01,526 - src.feature_engineering - INFO - Calculating Max Drawdowns

In [24]:
print("-" * 30)
print("Risk Metrics:")
print(f"Annualised Volatility: {volatility:.2%}")
print(f"Sharpe Ratio:          {sharpe_ratio:.2f}")
print(f"Max Drawdown:          {max_drawdown:.2%}")

------------------------------
Risk Metrics:
Annualised Volatility: 18.68%
Sharpe Ratio:          -1.05
Max Drawdown:          -27.78%

### PHASE 4 - RISK SCORING

In [25]:
from src.risk_scorer import calculate_risk_score
calculate_risk_score(volatility, sharpe_ratio, max_drawdown)

2026-05-07 00:19:01,549 - src.risk_scorer - INFO - Calculating the risk score
2026-05-07 00:19:01,550 - src.risk_scorer - INFO - Assigned label "Medium" with score 49

{'risk_score': 49, 'risk_label': 'Medium'}